# .github/workflows/main.yml CORREGIDO
name: Ejecutar Script Python Periodicamente

on:
  schedule:
    - cron: "*/1 * * * *"  # cada 5 minutos
  workflow_dispatch:      # permite ejecutar manualmente

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python index.py  # <-- ¡ESTA ES LA LÍNEA CORREGIDA!
